### PR TITLE
Add more git options + hub support

### PR DESCRIPTION
**Pull request by Raynos**
- added a `--help` cli arg for printing usage
- made `init-repo.js` more configurable for git workflows
- allow creating a repo using `hub` instead of `lib/create-repo.js`
- add a `--no-create` option to only do `init-repo.js` and not creating github remote
- refactored test runner to be `node`  + `tap-spec` instead of `tap`. I can change that to `tap-dot` instead if wanted.

This solves https://github.com/thlorenz/gitify/issues/1

I want to get the git `init-repo.js` flow double checked by a coworker before this is ready for merge.

### CODE REVIEW

**Comment by Raynos** [comment]
I tried to make the commits atomic.

This change is probably easier to review commit by commit.

**Comment by Raynos** [comment]
@thlorenz fixed a bug and added a --set-upstream flag.

This is ready for review / merge at this point :)

**Comment by thlorenz** [comment]
Cool, will have a look and merge this tomorrow at the latest, thanks.

**Comment by thlorenz** [comment]
I merged this into options-hub branch, tests pass and all seems well.
Unfortunately when trying this I got an error telling me repo exists already (although `foo` is not a repo I own already) - see below.

So things to do before merging into master:
- make it work (solve the issue I mentioned)
- add documentation for added features (both for API and cli usage) to readme

```
~/dev/js/projects/tmp/foo
➝  gitify
loaded config from:  /Users/thlorenz/.config/gitify.js
{ err:
   { message: 'Validation Failed',
     documentation_url: 'https://developer.github.com/v3/repos/#create',
     errors: [ [Object] ] },
  statusCode: 422 }
[ { resource: 'Repository',
    code: 'custom',
    field: 'name',
    message: 'name already exists on this account' } ]
```

**Comment by thlorenz** [comment]
I also cannot run your example:

Even if turning of `hub` always, I still get:

```
loaded config from:  /Users/thlorenz/.config/gitify.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

shell returned 8
```

**Comment by thlorenz** [comment]
Somehow though your example still created a repo, but still errored as I showed above.

However my example still works.
But the cli seems hosed somehow.

**Comment by thlorenz** [comment]
Hey any news on this? Do you still need this merged (after it's fixed)?

**Comment by Raynos** [comment]
@thlorenz we have an internal copy paste in one of our projects, we'll open source it eventually.

Once we get to that point I'll make a fresh PR into gitify since it's diverged. 

I'll also write better tests :)

**Comment by thlorenz** [comment]
Cool sounds good. Thanks.

**Pull request closed without merging**
